url: "https://adam.schmideg.net"
highlighter: rouge
permalink: /:year/:month/:title
remote_theme: dieghernan/chulapa
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
chulapa-skin: 
  skin: hootstrap
search:
  provider: simplesearch

gtag_id: 'UA-6932086-1'
analytics_id: 'UA-6932086-1'
